language: php

sudo: false

branches:
  except:
    - /^analysis-.*$/

matrix:
    fast_finish: true
    include:
        - php: '7.3'
        - php: '7.2'
        - php: '7.1'
        - php: 7.4snapshot

before_install:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

before_script:
    - composer install --prefer-dist --no-interaction --no-scripts --no-progress

script:
    - vendor/bin/phpunit --coverage-clover build/coverage-clover.xml

after_script:
    - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage-clover.xml
    - vendor/bin/php-coveralls -v -c .coveralls.yml
